### ISSUE TITLE
ESDoc Hosting Service

### ISSUE THREAD

**Issue by h13i32maru** [Voronar/NativeWidgets#1]
Hi!
I am ESDoc developer and thanks for using ESDoc :smile: 

I released [ESDoc Hosting Service](https://doc.esdoc.org) :rocket: 
Register your repository Git URL, this service automatically generate documentation.
If you are interested, please try to use it.
Thanks

**Comment by Voronar** [comment]
Thanks. I will certainly try it!

On Sun, Aug 23, 2015 at 4:49 PM, Ryo Maruyama <notifications@github.com>
wrote:

> Hi!
> I am ESDoc developer and thanks for using ESDoc [image: :smile:]
>
> I released ESDoc Hosting Service <https://doc.esdoc.org> [image: :rocket:]
> Register your repository Git URL, this service automatically generate
> documentation.
> If you are interested, please try to use it.
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Voronar/NativeWidgets/issues/1>.
>



-- 
*С уважением*
*Кирилл Халитов*

**Comment by h13i32maru** [comment]
I am glad :sparkles:
